language: java
sudo: false
jdk:
- oraclejdk7
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install:
  - ./gradlew assemble
before_script:
  - echo -e "gradle.publish.key=$APIKEY\ngradle.publish.secret=$APISECRET" > $HOME/.gradle/gradle.properties
  - mkdir $HOME/install
  - wget https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-5.6.zip -O $HOME/install/sonarqube-5.6.zip
  - unzip $HOME/install/sonarqube-5.6.zip -d $HOME -q
  - wget https://github.com/SonarQubeCommunity/sonar-css/releases/download/2.0/sonar-css-plugin.jar -O $HOME/sonarqube-5.6/extensions/plugins/sonar-css-plugin.jar
  - $HOME/sonarqube-5.6/bin/linux-x86-64/sonar.sh start
script:
  - ./buildTravis.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/19d1516a0a3505ee7489
    on_success: change
    on_failure: always
    on_start: never



